Updates icons for android and triggers release

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,9 +1,10 @@
 name: Spotlight Mobile CI/CD
 on:
-  push:
-    branches: [main]
-    paths-ignore:
-      - ".github/**"
+  workflow_dispatch:
+  # push:
+  #   branches: [main]
+  #   paths-ignore:
+  #     - ".github/**"
 
 env:
   JAVA_VERSION: "11"
@@ -12,40 +13,40 @@ env:
   ios_version_code: 0
 
 jobs:
-  android-test:
-    runs-on: macos-latest
+  # android-test:
+  #   runs-on: macos-latest
 
-    steps:
-      - name: checkout
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v3
 
-      - name: Install Appium
-        run: |
-          npm install -g appium@next
-          appium driver install uiautomator2
+  #     - name: Install Appium
+  #       run: |
+  #         npm install -g appium@next
+  #         appium driver install uiautomator2
         
-      - name: Run tests
-        uses: reactivecircus/android-emulator-runner@v2
-        with:
-          api-level: 26
-          target: google_apis
-          arch: x86_64
-          profile: pixel_xl
-          cores: 2
-          ram-size: 4096M 
-          sdcard-path-or-size: 2000M
-          avd-name: Pixel
-          force-avd-creation: false
-          emulator-options: -no-window -gpu guest -noaudio -no-boot-anim -camera-back none -accel on
-          disable-animations: true
-          script: mvn test -PRegression -f ./tests/pom.xml -q
+  #     - name: Run tests
+  #       uses: reactivecircus/android-emulator-runner@v2
+  #       with:
+  #         api-level: 26
+  #         target: google_apis
+  #         arch: x86_64
+  #         profile: pixel_xl
+  #         cores: 2
+  #         ram-size: 4096M 
+  #         sdcard-path-or-size: 2000M
+  #         avd-name: Pixel
+  #         force-avd-creation: false
+  #         emulator-options: -no-window -gpu guest -noaudio -no-boot-anim -camera-back none -accel on
+  #         disable-animations: true
+  #         script: mvn test -PRegression -f ./tests/pom.xml -q
 
-      - name: Archive test results
-        uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-          name: functional-test-report
-          path: tests/reports
+  #     - name: Archive test results
+  #       uses: actions/upload-artifact@v3
+  #       if: success() || failure()
+  #       with:
+  #         name: functional-test-report
+  #         path: tests/reports
 
   android:
     needs: android-test
@@ -163,141 +164,141 @@ jobs:
           name: android-integration-released-version
           path: ./app/AndroidVersionCode.txt
 
-  ios:
-    name: Build and Release IPA
-    runs-on: macos-latest
-    defaults:
-      run:
-        working-directory: ${{ env.WORKING_DIR }}
+  # ios:
+  #   name: Build and Release IPA
+  #   runs-on: macos-latest
+  #   defaults:
+  #     run:
+  #       working-directory: ${{ env.WORKING_DIR }}
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
       
-      - name: Download Version artifact
-        uses: dawidd6/action-download-artifact@v2
-        with:
-          github_token: ${{secrets.GITHUB_TOKEN}}
-          workflow: main.yml
-          name: ios-integration-released-version
-          path: ./app/
-          search_artifacts: true
-          workflow_conclusion: ""
-          if_no_artifact_found: ignore
+  #     - name: Download Version artifact
+  #       uses: dawidd6/action-download-artifact@v2
+  #       with:
+  #         github_token: ${{secrets.GITHUB_TOKEN}}
+  #         workflow: main.yml
+  #         name: ios-integration-released-version
+  #         path: ./app/
+  #         search_artifacts: true
+  #         workflow_conclusion: ""
+  #         if_no_artifact_found: ignore
 
-      - name: Check file existence
-        id: check_files
-        uses: andstor/file-existence-action@v2
-        with:
-          files: "./app/iOSVersionCode.txt"
+  #     - name: Check file existence
+  #       id: check_files
+  #       uses: andstor/file-existence-action@v2
+  #       with:
+  #         files: "./app/iOSVersionCode.txt"
       
-      - name: File exists
-        if: steps.check_files.outputs.files_exists == 'true'
-        run: echo "ios_version_code=$(cat iOSVersionCode.txt | cut -d "-" -f2-)" >> $GITHUB_ENV
+  #     - name: File exists
+  #       if: steps.check_files.outputs.files_exists == 'true'
+  #       run: echo "ios_version_code=$(cat iOSVersionCode.txt | cut -d "-" -f2-)" >> $GITHUB_ENV
 
-      - name: Install the Apple certificate and provisioning profile
-        env:
-          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
-          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
-          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
-          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-          AUTH_KEY_BASE64: ${{ secrets.AUTH_KEY_BASE64 }}
-        run: |
-          # create variables
-          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
-          echo $CERTIFICATE_PATH
-          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
-          echo $PP_PATH
-          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
-          echo $KEYCHAIN_PATH
-          AUTH_KEY_PATH=$RUNNER_TEMP/auth_key.p8
-          echo $AUTH_KEY_PATH
+  #     - name: Install the Apple certificate and provisioning profile
+  #       env:
+  #         BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
+  #         P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
+  #         BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
+  #         KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+  #         AUTH_KEY_BASE64: ${{ secrets.AUTH_KEY_BASE64 }}
+  #       run: |
+  #         # create variables
+  #         CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
+  #         echo $CERTIFICATE_PATH
+  #         PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
+  #         echo $PP_PATH
+  #         KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+  #         echo $KEYCHAIN_PATH
+  #         AUTH_KEY_PATH=$RUNNER_TEMP/auth_key.p8
+  #         echo $AUTH_KEY_PATH
 
-          # import certificates and provisioning profile from secrets
-          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
-          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
-          echo -n "$AUTH_KEY_BASE64" | base64 --decode --output $AUTH_KEY_PATH
+  #         # import certificates and provisioning profile from secrets
+  #         echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
+  #         echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
+  #         echo -n "$AUTH_KEY_BASE64" | base64 --decode --output $AUTH_KEY_PATH
 
-          # create temporary keychain
-          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
-          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+  #         # create temporary keychain
+  #         security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+  #         security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+  #         security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
 
-          # import certificate to keychain
-          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
-          security list-keychain -d user -s $KEYCHAIN_PATH
+  #         # import certificate to keychain
+  #         security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+  #         security list-keychain -d user -s $KEYCHAIN_PATH
 
-          # apply provisioning profile
-          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
+  #         # apply provisioning profile
+  #         mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
+  #         cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
 
-          echo "KEY_PATH=$AUTH_KEY_PATH" >> $GITHUB_ENV
+  #         echo "KEY_PATH=$AUTH_KEY_PATH" >> $GITHUB_ENV
 
-      - name: Setup Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16.x
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16.x
       
-      - name: Update iOS Bundle Version
-        id: updated_ios_version
-        uses: actions/github-script@v6
-        with:
-          script: |
-            return parseInt("${{ env.ios_version_code }}") + 1
+  #     - name: Update iOS Bundle Version
+  #       id: updated_ios_version
+  #       uses: actions/github-script@v6
+  #       with:
+  #         script: |
+  #           return parseInt("${{ env.ios_version_code }}") + 1
 
-      - name: Update Plist version for iOS
-        uses: damienaicheh/update-ios-version-info-plist-action@v1.0.0
-        with:
-          info-plist-path: "app/ios/App/App/Info.plist"
-          bundle-version: "${{steps.updated_ios_version.outputs.result}}"
-          bundle-short-version-string: "1.0.${{steps.updated_ios_version.outputs.result}}"
-          print-file: true
+  #     - name: Update Plist version for iOS
+  #       uses: damienaicheh/update-ios-version-info-plist-action@v1.0.0
+  #       with:
+  #         info-plist-path: "app/ios/App/App/Info.plist"
+  #         bundle-version: "${{steps.updated_ios_version.outputs.result}}"
+  #         bundle-short-version-string: "1.0.${{steps.updated_ios_version.outputs.result}}"
+  #         print-file: true
 
-      - name: Install Ionic
-        run: npm install -g @ionic/cli
+  #     - name: Install Ionic
+  #       run: npm install -g @ionic/cli
 
-      - name: Install app dependencies
-        run: npm install
+  #     - name: Install app dependencies
+  #       run: npm install
 
-      - name: Build App
-        run: npm run build
+  #     - name: Build App
+  #       run: npm run build
 
-      - name: Capacitor copy
-        run: ionic capacitor copy ios && ionic capacitor update ios
+  #     - name: Capacitor copy
+  #       run: ionic capacitor copy ios && ionic capacitor update ios
 
-      - name: Build iOS
-        run: ionic capacitor build ios --minifycss --optimizejs --minifyjs --no-open --release
+  #     - name: Build iOS
+  #       run: ionic capacitor build ios --minifycss --optimizejs --minifyjs --no-open --release
       
-      # - name: Build iOS Production
-      #   run: ionic capacitor build ios --minifycss --optimizejs --minifyjs --no-open --release --prod
+  #     # - name: Build iOS Production
+  #     #   run: ionic capacitor build ios --minifycss --optimizejs --minifyjs --no-open --release --prod
 
-      - name: Build with xCode
-        run: xcodebuild -workspace ios/App/App.xcworkspace -scheme App clean archive -configuration Release -sdk iphoneos DEVELOPMENT_TEAM=${{secrets.APPLE_DEV_TEAM}} -archivePath ios/App/App.xcarchive -authenticationKeyIssuerID ${{secrets.AUTH_KEY_ISSUER_ID}} -authenticationKeyID ${{secrets.KEY_ID}} -authenticationKeyPath ${{ env.KEY_PATH }} -allowProvisioningUpdates
+  #     - name: Build with xCode
+  #       run: xcodebuild -workspace ios/App/App.xcworkspace -scheme App clean archive -configuration Release -sdk iphoneos DEVELOPMENT_TEAM=${{secrets.APPLE_DEV_TEAM}} -archivePath ios/App/App.xcarchive -authenticationKeyIssuerID ${{secrets.AUTH_KEY_ISSUER_ID}} -authenticationKeyID ${{secrets.KEY_ID}} -authenticationKeyPath ${{ env.KEY_PATH }} -allowProvisioningUpdates
 
-      - name: Generate IPA file
-        run: |
-          cd ios/App/App.xcarchive/Products/Applications
-          mkdir Payload
-          cp -R App.app Payload
-          zip -qyr App.ipa ./Payload
+  #     - name: Generate IPA file
+  #       run: |
+  #         cd ios/App/App.xcarchive/Products/Applications
+  #         mkdir Payload
+  #         cp -R App.app Payload
+  #         zip -qyr App.ipa ./Payload
 
-      - name: Upload IPA to TestApp.io
-        uses: testappio/github-action@v5
-        with:
-          api_token: ${{secrets.TESTAPPIO_API_TOKEN}}
-          app_id: ${{secrets.TESTAPPIO_APP_ID}}
-          file: app/ios/App/App.xcarchive/Products/Applications/App.ipa
-          release_notes: "Testing manual release notes..."
-          git_release_notes: false
-          include_git_commit_id: false
-          notify: true
+  #     - name: Upload IPA to TestApp.io
+  #       uses: testappio/github-action@v5
+  #       with:
+  #         api_token: ${{secrets.TESTAPPIO_API_TOKEN}}
+  #         app_id: ${{secrets.TESTAPPIO_APP_ID}}
+  #         file: app/ios/App/App.xcarchive/Products/Applications/App.ipa
+  #         release_notes: "Testing manual release notes..."
+  #         git_release_notes: false
+  #         include_git_commit_id: false
+  #         notify: true
       
-      - name: Print deployed Release Version
-        run: |
-          echo "Build-${{steps.updated_ios_version.outputs.result}}" > ./iOSVersionCode.txt
+  #     - name: Print deployed Release Version
+  #       run: |
+  #         echo "Build-${{steps.updated_ios_version.outputs.result}}" > ./iOSVersionCode.txt
 
-      - name: Archive iOS
-        uses: actions/upload-artifact@v3
-        with:
-          name: ios-integration-released-version
-          path: ./app/iOSVersionCode.txt
+  #     - name: Archive iOS
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ios-integration-released-version
+  #         path: ./app/iOSVersionCode.txt
